// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd983GqM0sQjM2qU2U1vJrrBwBGS1mtlQ',
    appId: '1:43595354963:web:cc62024baed752e8ef47a6',
    messagingSenderId: '43595354963',
    projectId: 'carapp99-1cced',
    authDomain: 'carapp99-1cced.firebaseapp.com',
    storageBucket: 'carapp99-1cced.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEZ4zGQLsMRkSzGuFgAHUMErHsVtnh3-Q',
    appId: '1:43595354963:android:9455eed212b0828eef47a6',
    messagingSenderId: '43595354963',
    projectId: 'carapp99-1cced',
    storageBucket: 'carapp99-1cced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSavy7-0UmXc4x_FmtTpE5u3n5GmIxq1c',
    appId: '1:43595354963:ios:a0df4a90e7546fbfef47a6',
    messagingSenderId: '43595354963',
    projectId: 'carapp99-1cced',
    storageBucket: 'carapp99-1cced.appspot.com',
    iosClientId: '43595354963-8vmpqlsnvk1an0kr994ohqar0m8u94bd.apps.googleusercontent.com',
    iosBundleId: 'com.jobroloff',
  );
}
